name: Publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upload
        if: github.ref == 'refs/heads/master'
        uses: appleboy/scp-action@v0.0.5
        with:
          host: iad1-shared-e1-05.dreamhost.com
          username: ${{ secrets.BANDBOX_FTP_USERNAME }}
          password: ${{ secrets.BANDBOX_FTP_PASSWORD }}
          port: 22  # SFTP
          source: "./"
          target: "~/time.polyforest.com/"
          strip_components: 0